### ISSUE TITLE
WebTestClient/WebClient does not work properly with @AutoConfigureObservability

### ISSUE THREAD

**Issue by surmabck** [micrometer-metrics/tracing#175]
When test is annotated with `@AutoConfigureObservability` and `management.baggage.correlation.fields` property has any value, then even simple GET request via WebTestClient (probably WebClient too) is going to fail with:

```
java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false
	at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86)
...
```

Tested it with brave reporter only.

Reproducer is available here: https://github.com/surmabck/spring-boot-3xx-micrometer-issues/blob/main/src/test/kotlin/com/example/demo/DemoApplicationTests.kt#L29

**Comment by davidmelia** [comment]
@marcingrzejszczak This bug is partially fixed in 3.0.7 however still exists if spring security is on the classpath see https://github.com/davidmelia/spring-boot-kafka-consumer-tracing/tree/hooks-security-brave-flush-error

The only way i've found to workaround this is to declare

```
  @Bean
  @Order(1)
  CorrelationScopeCustomizer myCorrelationFieldsCorrelationScopeCustomizer(TracingProperties tracingProperties) {
    return (builder) -> {
      List<String> correlationFields = tracingProperties.getBaggage().getCorrelation().getFields();
      for (String field : correlationFields) {
        builder.add(CorrelationScopeConfig.SingleCorrelationField.newBuilder(BaggageField.create(field))
                .build());
      }
    };
  }
```

```
management:
  tracing:
    baggage:
      correlation:
        enabled: false
```

**Comment by marcingrzejszczak** [comment]
Please do with a reproducer. I think we have a solution to fix all of these but we want to be sure that we have tested that thoroughly

**Comment by kioyong** [comment]
i have same issue when run Spring Mock Mvc test and set management.tracing.baggage.correlation.fields
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@AutoConfigureObservability
class PingControllerTest{

    @Test
    void pingGet(@Autowired MockMvc mvc) throws Exception {
        mvc.perform(get("/ping"))
                .andExpect(status().isOk());
    }
}
```

```
java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false

	at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86)
	at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37)
	at io.micrometer.tracing.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:119)
	at io.micrometer.tracing.handler.RevertingScope.close(RevertingScope.java:39)
	at io.micrometer.tracing.handler.TracingObservationHandler.onScopeClosed(TracingObservationHandler.java:137)
	at io.micrometer.observation.ObservationHandler$FirstMatchingCompositeObservationHandler.onScopeClosed(ObservationHandler.java:181)
	at io.micrometer.observation.SimpleObservation.notifyOnScopeClosed(SimpleObservation.java:264)
	at io.micrometer.observation.SimpleObservation.access$100(SimpleObservation.java:38)
	at io.micrometer.observation.SimpleObservation$SimpleScope.close(SimpleObservation.java:319)
	at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:478)
	at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:338)
	at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:80)
```

**Comment by marcingrzejszczak** [comment]
That should be fixed in the latest Spring Framework and [this Spring Boot release](https://github.com/spring-projects/spring-boot/releases/tag/v3.0.8). Can you double check that if you add to one of your configs

```java
@Autowired
		ObservationRegistry observationRegistry;

		@PostConstruct
		void setup() {
			ObservationThreadLocalAccessor.getInstance().setObservationRegistry(
					Objects.requireNonNull(observationRegistry));
		}
```

the problems go away?

**Comment by davidmelia** [comment]
@marcingrzejszczak  I upgraded https://github.com/davidmelia/spring-boot-kafka-consumer-tracing/tree/hooks-security-brave-flush-error to spring boot 3.0.8 and the error has gone away.

Thanks :-)

**Comment by marcingrzejszczak** [comment]
You have no idea how I'm happy to hear that :)
