### ISSUE TITLE
`ObservationThreadLocalAccessor.setValue()` starts `NullObservation` but doesn't stop it

### ISSUE THREAD

**Issue by kzander91** [micrometer-metrics/tracing#296]
I'm not sure if this is an issue with Spring Webflux, Micrometer Tracing or Reactor (this started after upgrading from Spring Boot 3.0 to 3.1, which brought new versions of all three libs).

When running with assertions enabled (`-ea`), the following test fails (without assertions, it just logs a warning):
```java
@Test
void reproducer() {
    Hooks.enableAutomaticContextPropagation();
    WebClient.create()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```
The logged warning/thrown error is `00:11:57.344 [main] WARN io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor -- Observation <{name=null(null), error=null, context=name='null', contextualName='null', error='null', lowCardinalityKeyValues=[], highCardinalityKeyValues=[], map=[], parentObservation=null}> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks`

While debugging this I found the following in `ObservationThreadLocalAccessor`:
https://github.com/micrometer-metrics/micrometer/blob/9d368be199d3da8c82817994c82882e4c28f93f8/micrometer-observation/src/main/java/io/micrometer/observation/contextpropagation/ObservationThreadLocalAccessor.java#L111-L116
Reactor calls this method when automatic context propagation is enabled (via `ContextSnapshotFactory.setThreadLocalsFrom(context)`).
This seems suspicious to me as an observation is started here that is later still around, causing the above warning/error.

---

Dependencies:
```xml
<dependencies>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-webflux</artifactId>
        <version>6.0.10</version>
    </dependency>
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-tracing</artifactId>
        <version>1.1.2</version>
    </dependency>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>5.9.3</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

---
Minimal Project (extract and run `./mvnw test`):
[demo.zip](https://github.com/micrometer-metrics/tracing/files/11861129/demo.zip)

This may be related to #175.

**Comment by marcingrzejszczak** [comment]
Have you added in your code the following snippet?

```java
@Configuration
class Config {

@Autowired ObservationRegistry registry;

@PostConstruct
void setup() {
  ObservationThreadLocalAccessor.getInstance().setObservationRegistry(registry);
}


}
```

**Comment by marcingrzejszczak** [comment]
I've opened your project. Because you have nothing set up in terms of ObservationRegistry (no tracing, metrics handlers etc.) you should just set

```
ObservationThreadLocalAccessor.getInstance().setObservationRegistry(ObservationRegistry.NOOP);
```

**Comment by kzander91** [comment]
My example code is intentionally minimal, I arrived at those dependencies while successively removing dependencies from my actual project to see if any of those are causing the issue.
I don't even need any Spring (Boot) configuration to reproduce this; the posted code snippet is all there is: just enable automatic context propagation and use a `WebClient` to perform a call.

---

I have tried a few combinations of setting the registry:

**Don't set anything explicitly**
```java
@Test
void reproducer() {
    Hooks.enableAutomaticContextPropagation();
    WebClient.create()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```
Result:
```
java.lang.AssertionError: Observation <{name=null(null), error=null, context=name='null', contextualName='null', error='null', lowCardinalityKeyValues=[], highCardinalityKeyValues=[], map=[], parentObservation=null}> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:148)
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:32)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.resetThreadLocalValue(DefaultContextSnapshot.java:144)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.close(DefaultContextSnapshot.java:136)
        at reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.request(MonoContextWriteRestoringThreadLocals.java:156)
```

**Set `NOOP` in `ObservationThreadLocalAccessor`**
```java
@Test
void reproducer() {
    ObservationThreadLocalAccessor.getInstance().setObservationRegistry(ObservationRegistry.NOOP);
    Hooks.enableAutomaticContextPropagation();
    WebClient.create()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```
Result:
```
java.lang.NullPointerException: Cannot invoke "io.micrometer.observation.Observation.parentObservation(io.micrometer.observation.Observation)" because "observation" is null
        at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$11(DefaultWebClient.java:444)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
        at reactor.core.publisher.Mono.block(Mono.java:1711)
        at com.example.demo.ReproducerTest.reproducer(ReproducerTest.java:20)
```

**Set `NOOP` in `ObservationThreadLocalAccessor` and `WebClient`**
```java
@Test
void reproducer() {
    ObservationThreadLocalAccessor.getInstance().setObservationRegistry(ObservationRegistry.NOOP);
    Hooks.enableAutomaticContextPropagation();
    WebClient.builder()
            .observationRegistry(ObservationRegistry.NOOP)
            .build()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```
Result:
```
java.lang.NullPointerException: Cannot invoke "io.micrometer.observation.Observation.parentObservation(io.micrometer.observation.Observation)" because "observation" is null
        at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$11(DefaultWebClient.java:444)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
        at reactor.core.publisher.Mono.block(Mono.java:1711)
        at com.example.demo.ReproducerTest.reproducer(ReproducerTest.java:22)
```
**Create real registry and set in `ObservationThreadLocalAccessor` and `WebClient`**
```java
@Test
void reproducer() {
    ObservationRegistry observationRegistry = ObservationRegistry.create();
    ObservationThreadLocalAccessor.getInstance().setObservationRegistry(observationRegistry);
    Hooks.enableAutomaticContextPropagation();
    WebClient.builder()
            .observationRegistry(observationRegistry)
            .build()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```
Result:
```
java.lang.AssertionError: Observation <{name=null(null), error=null, context=name='null', contextualName='null', error='null', lowCardinalityKeyValues=[], highCardinalityKeyValues=[], map=[], parentObservation=null}> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:148)
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:32)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.resetThreadLocalValue(DefaultContextSnapshot.java:144)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.close(DefaultContextSnapshot.java:136)
        at reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.request(MonoContextWriteRestoringThreadLocals.java:156)
```

---

The NullPointerExceptions are happening because the `Observation.NOOP` field isn't initialized for some reason. If I explicitly initialize it in my test, I'm back to the original error with a few more warnings along the way:
```java
@Test
void reproducer() {
    System.out.println("Init: " + Observation.NOOP);
    ObservationThreadLocalAccessor.getInstance().setObservationRegistry(ObservationRegistry.NOOP);
    Hooks.enableAutomaticContextPropagation();
    WebClient.create()
            .get()
            .uri("https://httpbin.org/get")
            .retrieve()
            .bodyToMono(String.class)
            .block();
}
```

Logs & Error:
```
Init: io.micrometer.observation.NoopObservation@35ef1869
Juni 26, 2023 10:18:52 AM io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor restore
WARNUNG: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
Juni 26, 2023 10:18:52 AM io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor restore
WARNUNG: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
Juni 26, 2023 10:18:52 AM io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor restore
WARNUNG: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
Juni 26, 2023 10:18:52 AM io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor restore
WARNUNG: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
[ERROR] (main) Operator called default onErrorDropped - java.lang.AssertionError: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
java.lang.AssertionError: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:148)
        at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:32)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.resetThreadLocalValue(DefaultContextSnapshot.java:144)
        at io.micrometer.context.DefaultContextSnapshot$DefaultScope.close(DefaultContextSnapshot.java:136)
        at reactor.core.publisher.MonoContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.onError(MonoContextWriteRestoringThreadLocals.java:127)
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:119)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
        at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:232)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:71)
        at reactor.core.publisher.MonoContextWriteRestoringThreadLocals.subscribe(MonoContextWriteRestoringThreadLocals.java:44)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
        at reactor.core.publisher.Mono.block(Mono.java:1711)
        at com.example.demo.ReproducerTest.reproducer(ReproducerTest.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
        at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
        Suppressed: java.lang.AssertionError: Observation <io.micrometer.observation.NoopObservation@35ef1869> to which we're restoring is not the same as the one set as this scope's parent observation <null> . Most likely a manually created Observation has a scope opened that was never closed. This may lead to thread polluting and memory leaks
                at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:148)
                at io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.restore(ObservationThreadLocalAccessor.java:32)
                at io.micrometer.context.DefaultContextSnapshot$DefaultScope.resetThreadLocalValue(DefaultContextSnapshot.java:144)
                at io.micrometer.context.DefaultContextSnapshot$DefaultScope.close(DefaultContextSnapshot.java:136)
                at reactor.core.publisher.MonoContextWriteRestoringThreadLocals.subscribe(MonoContextWriteRestoringThreadLocals.java:45)
                ... 75 more
```

**Comment by marcingrzejszczak** [comment]
```
java.lang.NullPointerException: Cannot invoke "io.micrometer.observation.Observation.parentObservation(io.micrometer.observation.Observation)" because "observation" is null
        at org.springframework.web.reactive.function.client.DefaultWebClient$DefaultRequestBodyUriSpec.lambda$exchange$11(DefaultWebClient.java:444)
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:47)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495)
        at reactor.core.publisher.Mono.block(Mono.java:1711)
        at com.example.demo.ReproducerTest.reproducer(ReproducerTest.java:20)
```

this is crazy cause that field can't be null (I had the same problem in my IDE), however this works fine from the terminal (`./mvnw clean install` was ran successfully without any warnings)

cc @chemicL

**Comment by marcingrzejszczak** [comment]
Can you add this @PascalSchumacher ?

```java
@Configuration
class Config {

 @Autowired ObservationRegistry registry;

 @PostConstruct
 void setup() {
  ObservationThreadLocalAccessor.getInstance().setObservationRegistry(registry);
 }


}
```

**Comment by PascalSchumacher** [comment]
@marcingrzejszczak Sure! I added the configuration class you posted, but sadly it does not change the behavior.

**Comment by marcingrzejszczak** [comment]
Wat? That's super strange. Do you have a reproducer?

**Comment by xsreality** [comment]
I am facing the same error as @PascalSchumacher when trying to upgrade to SB 3.1.1 today.

I created a reproducer app here: https://github.com/xsreality/micrometer-tracing-gh-296/

**Comment by xsreality** [comment]
Also curious how I can write a unit/integration test to capture this behaviour? Looking through the docs (https://micrometer.io/docs/tracing#_testing), the integration test seems to be a good fit. But the `SampleTestRunner` seems to require both WaveFront and Zipkin to work.

**Comment by marcingrzejszczak** [comment]
I think this error is related to this one https://github.com/micrometer-metrics/micrometer/issues/3942 , can you check against latest micrometer snapshots to see if the problem goes away?

**Comment by kzander91** [comment]
I changed my dependencies to
```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webflux</artifactId>
            <version>6.0.10</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-observation</artifactId>
            <version>1.12.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.9.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>
```
But don't see any different behaviour. I retried all scenarios from [my previous comment](https://github.com/micrometer-metrics/tracing/issues/296#issuecomment-1606967449).
The snapshot version I got is micrometer-observation-1.12.0-20230628.082305-37.jar.

**Comment by kzander91** [comment]
I still have to manually initialize `Observation.NOOP` to avoid the NPE in `DefaultWebClient`, as mentioned above:
![grafik](https://github.com/micrometer-metrics/tracing/assets/61500114/fc924aef-630e-4109-82a6-8af0673e928e)

Otherwise, as said previously, the SNAPSHOTs didn't change anything for me. Maybe @PascalSchumacher or @xsreality can chip in.

**Comment by marcingrzejszczak** [comment]
OK so at least we got rid of the NPE. We need to now fix the actual exception

**Comment by kzander91** [comment]
Quick update: The latest snapshots have fixed the issues for me in my demo project and my actual project.
I tested 1.11.2-SNAPSHOT (micrometer) / 1.1.3-SNAPSHOT (tracing) and 1.12.0-SNAPSHOT (micrometer) / 1.2.0-SNAPSHOT (tracing).

**Comment by marcingrzejszczak** [comment]
@kzander91 So you no longer have any warnings and exceptions?

**Comment by kzander91** [comment]
Correct

**Comment by PascalSchumacher** [comment]
@marcingrzejszczak Not sure why this is closed, is there another issue for the non-working tracing and the warnings?

The reproducer created by @xsreality https://github.com/xsreality/micrometer-tracing-gh-296/ still logs the warnings when using the latest micrometer snapshots (just tried it).
