### ISSUE TITLE
Thread locals dirty with micrometer-tracing 1.1.5

### ISSUE THREAD

**Issue by rgarciapariente** [micrometer-metrics/tracing#378]
I found the issue when upgrading spring boot version to 3.1.4 and use micrometer-tracing 1.1.5. If I set "<micrometer-tracing.version>1.1.4</micrometer-tracing.version>" everything works again.

I have an example to reproduce https://github.com/rgarciapariente/micrometer-issue

This is the controller I'm testing with

```java
    @GetMapping(value = "/test-traceid")
    public Mono<ResponseEntity<String>> testTraceId() {
        return Mono.just("testTraceId")
                .handle((s, synchronousSink) -> {
                    System.out.println("("+Thread.currentThread().getName().toString()+")" + MDC.getCopyOfContextMap());
                    synchronousSink.next(MDC.get("traceId").toString());
                })
                .map(obj -> ResponseEntity.ok(obj.toString()));
    }
```

The first error I have encountered is in TestWithoutFilterTests#withAutomaticPropagationAllsWorksKOError1. If I launch more requests than threads I find that the traceId is repeated. This only happens when `Hooks.enableAutomaticContextPropagation()` is enabled. With it disabled it works fine

Execution with error, note that 651eb29c0eba2a3bee212436cf724e26 is repited
```
2023-10-05T14:56:57.362+02:00  INFO 1616 --- [           main] c.e.t.TestWithoutFilterTests             : Starting TestWithoutFilterTests using Java 17.0.6 with PID 1616 (started by n129586 in C:\Users\N129586.000\workspace\test-observability-error)
2023-10-05T14:56:57.365+02:00  INFO 1616 --- [           main] c.e.t.TestWithoutFilterTests             : No active profile set, falling back to 1 default profile: "default"
2023-10-05T14:56:58.920+02:00  INFO 1616 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-10-05T14:56:59.309+02:00  INFO 1616 --- [           main] c.e.t.TestWithoutFilterTests             : Started TestWithoutFilterTests in 2.205 seconds (process running for 3.326)
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
(parallel-1){traceId=651eb29c0eba2a3bee212436cf724e26, spanId=ee212436cf724e26}
(parallel-2){traceId=651eb29c46f3800134a4bfdb60376f9f, spanId=34a4bfdb60376f9f}
(parallel-3){traceId=651eb29cbc9d3a30630e10847c20c877, spanId=630e10847c20c877}
(parallel-4){traceId=651eb29cab0d25f1371a2f4daeedca17, spanId=371a2f4daeedca17}
(parallel-5){traceId=651eb29c955e813b5fa3a7d6ef6bc43c, spanId=5fa3a7d6ef6bc43c}
(parallel-6){traceId=651eb29caea0bc3e8a579e9f4966d0b1, spanId=8a579e9f4966d0b1}
(parallel-7){traceId=651eb29ce1278b6c71e3a03b8e0af076, spanId=71e3a03b8e0af076}
(parallel-8){traceId=651eb29c4f211aa23f895cb798d5f0e6, spanId=3f895cb798d5f0e6}
(parallel-9){traceId=651eb29c3ff42121adfeae4c3c57b77a, spanId=adfeae4c3c57b77a}
(parallel-10){traceId=651eb29c5def5832f2baa4992fb70786, spanId=f2baa4992fb70786}
(parallel-11){traceId=651eb29cbc84eb89be607df4c834ea66, spanId=be607df4c834ea66}
(parallel-12){traceId=651eb29c7d47a03e6e9b1186c8bab30b, spanId=6e9b1186c8bab30b}
(parallel-1){traceId=651eb29c0eba2a3bee212436cf724e26, spanId=abc89f34e8458c13}

org.opentest4j.AssertionFailedError: 
Expected :false
Actual   :true
```

Also, I found another error that I think is related. If I configured baggaged
```yaml
management:
  tracing:
    baggage:
      remote-fields:
        - field1
      correlation:
        fields:
          - field1
```
and activate `Hooks.enableAutomaticContextPropagation()` and put a filter that do a tap. For example:

```java
		@Bean
		WebFilter testWebFilter() {
			return (exchange, chain) ->  Mono.just(exchange)
					.tap(contextView -> new DefaultSignalListener<>() {
						@Override
						public void doOnNext(ServerWebExchange webExchange) {
							System.out.println("just checking MDC: " + MDC.getCopyOfContextMap().toString());
						}
					})
					.flatMap(chain::filter);
		}
```

then I get the next error

```
just checking MDC: {traceId=651eb4b50adddc0e8fad7cdb4bb1b9ba, spanId=8fad7cdb4bb1b9ba}
(parallel-4){traceId=651eb4b50adddc0e8fad7cdb4bb1b9ba, spanId=8fad7cdb4bb1b9ba}
2023-10-05T15:05:57.848+02:00 ERROR 30632 --- [     parallel-4] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.lang.AssertionError: Misalignment: popped updateScope false !=  expected false
	at brave.baggage.CorrelationFlushScope.popCurrentUpdateScope(CorrelationFlushScope.java:86) ~[brave-5.15.1.jar:na]
	at brave.baggage.CorrelationFlushScope.close(CorrelationFlushScope.java:37) ~[brave-5.15.1.jar:na]
	at io.micrometer.tracing.brave.bridge.BraveScope.close(BraveCurrentTraceContext.java:114) ~[micrometer-tracing-bridge-brave-1.1.5.jar:1.1.5]
```

It is the test TestWithFilterTests#withAutomaticPropagationAllsWorksKOError1

Many thanks & regards

**Comment by rgarciapariente** [comment]
Sorry. I don't see https://github.com/micrometer-metrics/tracing/issues/363, with 1.1.6-SNAPSHOT all is working ok

Thanks
