### ISSUE TITLE
ClassCastException: OtelTraceContext cannot be cast to SimpleTraceContext 

### ISSUE THREAD

**Issue by hetzijzo** [micrometer-metrics/tracing#573]
I migrated my Spring Boot 3.2 application. I get the following ClassCastException: 

```
java.lang.ClassCastException: class io.micrometer.tracing.otel.bridge.OtelTraceContext cannot be cast to class io.micrometer.tracing.test.simple.SimpleTraceContext (io.micrometer.tracing.otel.bridge.OtelTraceContext and io.micrometer.tracing.test.simple.SimpleTraceContext are in unnamed module of loader 'app')
	at io.micrometer.tracing.test.simple.SimpleCurrentTraceContext.newScope(SimpleCurrentTraceContext.java:66)
	at io.micrometer.tracing.test.simple.SimpleCurrentTraceContext.maybeScope(SimpleCurrentTraceContext.java:85)
	at io.micrometer.tracing.handler.TracingAwareMeterObservationHandler.onStop(TracingAwareMeterObservationHandler.java:83)
	at io.micrometer.observation.ObservationHandler$FirstMatchingCompositeObservationHandler.onStop(ObservationHandler.java:197)
	at io.micrometer.observation.SimpleObservation.lambda$notifyOnObservationStopped$0(SimpleObservation.java:268)
	at java.base/java.util.ArrayDeque$DescendingIterator.forEachRemaining(ArrayDeque.java:772)
	at io.micrometer.observation.SimpleObservation.notifyOnObservationStopped(SimpleObservation.java:268)
	at io.micrometer.observation.SimpleObservation.stop(SimpleObservation.java:188)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:123)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
```

I have the following dependencies included. 
- Spring Boot 3.2.2
- Micrometer version is 1.12.2

```xml
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-observation-test</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-bridge-otel</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-test</artifactId>
      <optional>true</optional>
    </dependency>
```

And this additional configuration

```java
@TestConfiguration
public class TestAutoConfiguration {
    @Bean
    @Primary
    Tracer simpleTracer() {
      return new SimpleTracer();
    }
}
```

1. I don't except a `OtelTraceContext` to be created, I don't know why this happens.
2. I don't except a explicit cast to SimpleTracer on https://github.com/micrometer-metrics/tracing/blob/a522d77a4015a5d3c8e4038982c08b4f567a1556/micrometer-tracing-tests/micrometer-tracing-test/src/main/java/io/micrometer/tracing/test/simple/SimpleCurrentTraceContext.java#L66

**Comment by marcingrzejszczak** [comment]
Why are you creating a `SimpleTracer` there? You would have to disable the current OpenTelemetry autoconfiguration and recreate the whole tracer setup using the simple tracer components and the like.

**Comment by hetzijzo** [comment]
I do need the `SimpleTracer` since I have (some) integration tests to verify and assert on some traces.

Switching off the `org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration` helps partially in my case. This causes the `org.springframework.boot.actuate.autoconfigure.tracing.NoopTracerAutoConfiguration` to create the missing Beans.

For the testcases that need `SimpleTracer` for verification I am currently required to create an additional Primary bean for it.
