### ISSUE TITLE
Allow holding back spans in SpanFilter

### ISSUE THREAD

**Issue by foaw** [micrometer-metrics/tracing#601]
As [`SpanFilter`](https://github.com/micrometer-metrics/tracing/blob/cc6bd1ba8a00eb391081ca7ab19caada54f45f56/micrometer-tracing/src/main/java/io/micrometer/tracing/exporter/SpanFilter.java) includes "filter" in its name, I expect that not only can spans be modified from it, but also completely undone, or suppressed. One could arguably do this some other way, but I think `SpanFilter` is the most sensible place, or an interface rather, for doing so.

As of the last commit, if null is returned, [`CompositeSpanExporter#export`](https://github.com/micrometer-metrics/tracing/blob/cc6bd1ba8a00eb391081ca7ab19caada54f45f56/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/CompositeSpanExporter.java#L67) will not handle it in any special way, and a `NullPointerException` will be thrown as it gets converted to `OtelFinishedSpan`.

https://github.com/micrometer-metrics/tracing/blob/cc6bd1ba8a00eb391081ca7ab19caada54f45f56/micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/CompositeSpanExporter.java#L69-L73

<details>
  <summary>If null is returned</summary>

```
java.lang.NullPointerException: Cannot read field "spanData" because "span" is null
	at io.micrometer.tracing.otel.bridge.OtelFinishedSpan.toOtel(OtelFinishedSpan.java:69) ~[micrometer-tracing-bridge-otel-1.2.2.jar:1.2.2]
	at io.micrometer.tracing.otel.bridge.CompositeSpanExporter.lambda$export$0(CompositeSpanExporter.java:71) ~[micrometer-tracing-bridge-otel-1.2.2.jar:1.2.2]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
	at io.micrometer.tracing.otel.bridge.CompositeSpanExporter.export(CompositeSpanExporter.java:72) ~[micrometer-tracing-bridge-otel-1.2.2.jar:1.2.2]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:327) ~[opentelemetry-sdk-trace-1.31.0.jar:1.31.0]
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:245) ~[opentelemetry-sdk-trace-1.31.0.jar:1.31.0]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```
</details>

**Comment by foaw** [comment]
Just found [`SpanExportingPredicate`](https://github.com/micrometer-metrics/tracing/blob/cc6bd1ba8a00eb391081ca7ab19caada54f45f56/micrometer-tracing/src/main/java/io/micrometer/tracing/exporter/SpanExportingPredicate.java) after coming back to this. Maybe it should be mentioned in the `SpanFilter` documentation?

**Comment by jonatan-ivanov** [comment]
Glad you found it. Are you interested in opening a PR?

You can find the docs in https://github.com/micrometer-metrics/tracing/tree/main/docs, and build them using `./gradlew antora`. I would base it off of the `1.2.x` branch and I think adding a note about them somewhere would make sense (basically what their javadoc says).
